### ISSUE TITLE
ERROR! couldn't resolve module/action 'sysctl'. This often indicates a misspelling, missing collection, or incorrect module path.

### ISSUE THREAD

**Issue by gratuxri** [LinuxHaus/ansible-lihas-proxmox#1]
IP=
ansible-playbook -i ${IP}, proxmox.yml
ERROR! couldn't resolve module/action 'sysctl'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '~/.ansible/roles/lihas_proxmox/tasks/main.yml': line 52, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    mode: 0444
- name: sysctl ipv4 forwarding default
  ^ here

**Comment by naukrii** [comment]
Whats the fix guys ?? i am facing same issue. using 2.9 version.

**Comment by gratuxri** [comment]
You need ansible.posix collection, like in https://github.com/LinuxHaus/ansible_lihas_proxmox/pull/5.patch

**Comment by ninp0** [comment]
To expand on this comment (which worked for me, thank you @gratuxri):

```
$ ansible-galaxy collection install ansible.posix
```
