### ISSUE TITLE
Fail on first try in lab, why are you not installing recommends?

### ISSUE THREAD

**Issue by gratuxri** [LinuxHaus/ansible-lihas-proxmox#3]
IP=
ansible-playbook -i ${IP}, proxmox.yml
/var/log/apt/history.log:
Start-Date: 2020-10-29  15:29:25
Commandline: /usr/bin/apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold install proxmox-ve -o APT::Install-Recommends=no
Install: proxmox-widget-toolkit:amd64 (2.3-1, automatic), libusbredirparser1:amd64 (0.8.0-1, automatic), libxdmcp6:amd64 (1:1.1.2-3, automatic), pve-kernel-5.4:amd64 (6.2-7, automatic), corosync:amd64 (3.0.4-pve1, automatic), python-six:amd64 (1.12.0-1, automatic), libcrypt-ssleay-perl:amd64 (0.73.06-1+b1, automatic), libgnutlsxx28:amd64 (3.6.7-4+deb10u5, automatic), libbytes-random-secure-perl:amd64 (0.29-1, automatic), libldb1:amd64 (2:1.5.1+really1.4.6-3, automatic), libnl-route-3-200:amd64 (3.4.0-1, automatic), fuse:amd64 (2.9.9-1+deb10u1, automatic), libradosstriper1:amd64 (12.2.11+dfsg1-2.1+b1, automatic), dosfstools:amd64 (4.1-2, automatic), libsnappy1v5:amd64 (1.1.7-1, automatic), ceph-common:amd64 (12.2.11+dfsg1-2.1+b1, automatic), glusterfs-client:amd64 (5.5-3, automatic), libpangoft2-1.0-0:amd64 (1.42.4-8~deb10u1, automatic), libcmap4:amd64 (3.0.4-pve1, automatic), postfix:amd64 (3.4.14-0+deb10u1, automatic), libgfdb0:amd64 (5.5-3, automatic), librrds-perl:amd64 (1.7.1-2, automatic), libpve-access-control:amd64 (6.1-3, automatic), fonts-font-awesome:amd64 (5.0.10+really4.7.0~dfsg-1, automatic), proxmox-mini-journalreader:amd64 (1.1-1, automatic), libcups2:amd64 (2.2.10-6+deb10u3, automatic), libterm-readline-gnu-perl:amd64 (1.36-1, automatic), python-configparser:amd64 (3.5.0b2-1, automatic), linux-libc-dev:amd64 (4.19.152-1, automatic), libxml-sax-base-perl:amd64 (1.09-1, automatic), libcurl4:amd64 (7.64.0-4+deb10u1, automatic), libpve-storage-perl:amd64 (6.2-9, automatic), proxmox-archive-keyring:amd64 (1.0, automatic), libdw1:amd64 (0.176-1.1, automatic), libacl1-dev:amd64 (2.2.53-4, automatic), libibverbs1:amd64 (22.1-1, automatic), libc6-dev:amd64 (2.28-10, automatic), libwbclient0:amd64 (2:4.9.5+dfsg-5+deb10u1, automatic), python3-jwt:amd64 (1.7.0-2, automatic), libjson-perl:amd64 (4.02000-1, automatic), libxml-sax-perl:amd64 (1.00+dfsg-1, automatic), python-requests:amd64 (2.21.0-1, automatic), pve-firmware:amd64 (3.1-3, automatic), ipset:amd64 (6.38-1.2, automatic), libgfapi0:amd64 (5.5-3, automatic), python-future:amd64 (0.16.0-1, automatic), libpixman-1-0:amd64 (0.36.0-1, automatic), libasound2-data:amd64 (1.1.8-1, automatic), bridge-utils:amd64 (1.6-2, automatic), libquorum5:amd64 (3.0.4-pve1, automatic), libcrypt-openssl-random-perl:amd64 (0.15-1+b1, automatic), liborc-0.4-0:amd64 (1:0.4.28-3.1, automatic), libxrender1:amd64 (1:0.9.10-1, automatic), pve-qemu-kvm:amd64 (5.1.0-3, automatic), zstd:amd64 (1.3.8+dfsg-3, automatic), libmime-base32-perl:amd64 (1.303-1, automatic), libogg0:amd64 (1.3.2-1+b1, automatic), libcephfs2:amd64 (12.2.11+dfsg1-2.1+b1, automatic), dtach:amd64 (0.9-4, automatic), libarchive13:amd64 (3.3.3-4+deb10u1, automatic), pve-kernel-5.4.65-1-pve:amd64 (5.4.65-1, automatic), libtirpc-common:amd64 (1.1.4-0.4, automatic), libanyevent-http-perl:amd64 (2.24-1, automatic), libavahi-common-data:amd64 (0.7-4+b1, automatic), librbd1:amd64 (12.2.11+dfsg1-2.1+b1, automatic), libpve-cluster-api-perl:amd64 (6.2-1, automatic), libpve-cluster-perl:amd64 (6.2-1, automatic), libavahi-common3:amd64 (0.7-4+b1, automatic), libpython2.7:amd64 (2.7.16-2+deb10u1, automatic), libfilesys-df-perl:amd64 (0.92-6+b4, automatic), libbabeltrace1:amd64 (1.5.6-2+deb10u1, automatic), pve-docs:amd64 (6.2-6, automatic), libgfrpc0:amd64 (5.5-3, automatic), libnuma1:amd64 (2.0.12-1, automatic), libdbi1:amd64 (0.9.0-5, automatic), libnet-dns-perl:amd64 (1.19-1, automatic), libpython3.7:amd64 (3.7.3-2+deb10u2, automatic), libuuid-perl:amd64 (0.28-1, automatic), pve-ha-manager:amd64 (3.1-1, automatic), libjs-jquery:amd64 (3.3.1~dfsg-3, automatic), libjs-underscore:amd64 (1.9.1~dfsg-1, automatic), libproxmox-acme-perl:amd64 (1.0.5, automatic), libthai-data:amd64 (0.1.28-2, automatic), libgfxdr0:amd64 (5.5-3, automatic), pve-firewall:amd64 (4.1-3, automatic), libjs-extjs:amd64 (6.0.1-10, automatic), ebtables:amd64 (2.0.10.4+snapshot20181205-3, automatic), python-certifi:amd64 (2018.8.24-1, automatic), liburcu6:amd64 (0.10.2-1, automatic), python-chardet:amd64 (3.0.4-3, automatic), libxcb-shm0:amd64 (1.13.1-2, automatic), rrdcached:amd64 (1.7.1-2, automatic), pve-container:amd64 (3.2-2, automatic), libxcb-render0:amd64 (1.13.1-2, automatic), librdmacm1:amd64 (22.1-1, automatic), proxmox-backup-client:amd64 (0.9.1-1, automatic), libconvert-asn1-perl:amd64 (0.27-2, automatic), libspice-server1:amd64 (0.14.2-4~pve6+1, automatic), libstring-shellquote-perl:amd64 (1.04-1, automatic), ssl-cert:amd64 (1.0.39, automatic), fontconfig-config:amd64 (2.13.1-2, automatic), libqb0:amd64 (1.0.5-1, automatic), libx11-6:amd64 (2:1.6.7-1+deb10u1, automatic), libopus0:amd64 (1.3-1, automatic), lzop:amd64 (1.03-4+b1, automatic), libanyevent-perl:amd64 (7.140-3, automatic), pve-cluster:amd64 (6.2-1, automatic), librados2-perl:amd64 (1.1-2, automatic), vncterm:amd64 (1.6-2, automatic), libjson-xs-perl:amd64 (3.040-1+b1, automatic), spiceterm:amd64 (3.1-1, automatic), cifs-utils:amd64 (2:6.8-2, automatic), libtalloc2:amd64 (2.1.14-2, automatic), python-rados:amd64 (12.2.11+dfsg1-2.1+b1, automatic), libfaketime:amd64 (0.9.7-3, automatic), libapt-pkg-perl:amd64 (0.1.34+b1, automatic), python-talloc:amd64 (2.1.14-2, automatic), python-prettytable:amd64 (0.7.2-4, automatic), libsm6:amd64 (2:1.2.3-1, automatic), attr:amd64 (1:2.4.48-4, automatic), libglusterfs-dev:amd64 (5.5-3, automatic), libmath-random-isaac-perl:amd64 (1.004-1, automatic), samba-libs:amd64 (2:4.9.5+dfsg-5+deb10u1, automatic), sqlite3:amd64 (3.27.2-3, automatic), gdisk:amd64 (1.0.3-1.1, automatic), libtcmalloc-minimal4:amd64 (2.7-1, automatic), pve-i18n:amd64 (2.2-1, automatic), libnet1:amd64 (1.1.6+dfsg-3.1, automatic), pve-xtermjs:amd64 (4.7.0-2, automatic), libpve-u2f-server-perl:amd64 (1.1-1, automatic), qrencode:amd64 (4.0.2-1, automatic), fontconfig:amd64 (2.13.1-2, automatic), libfuse3-3:amd64 (3.4.1-1+deb10u1, automatic), libio-multiplex-perl:amd64 (1.16-1, automatic), libstatgrab10:amd64 (0.91-1+b2, automatic), glusterfs-common:amd64 (5.5-3, automatic), libxau6:amd64 (1:1.0.8-1+b2, automatic), libclone-perl:amd64 (0.41-1+b1, automatic), libpangocairo-1.0-0:amd64 (1.42.4-8~deb10u1, automatic), libpulse0:amd64 (12.2-4+deb10u1, automatic), pve-manager:amd64 (6.2-12, automatic), psmisc:amd64 (23.2-1, automatic), xfsprogs:amd64 (4.20.0-1, automatic), libcaca0:amd64 (0.99.beta19-2.1, automatic), libxcb1:amd64 (1.13.1-2, automatic), libboost-iostreams1.67.0:amd64 (1.67.0-13+deb10u1, automatic), libxtst6:amd64 (2:1.2.3-1, automatic), fonts-glyphicons-halflings:amd64 (1.009~3.4.1+dfsg-1, automatic), libxi6:amd64 (2:1.7.9-1, automatic), libvotequorum8:amd64 (3.0.4-pve1, automatic), libvorbisenc2:amd64 (1.3.6-2, automatic), libnet-dbus-perl:amd64 (1.1.0-5+b1, automatic), libpve-guest-common-perl:amd64 (3.1-3, automatic), samba-common:amd64 (2:4.9.5+dfsg-5+deb10u1, automatic), libnet-ldap-perl:amd64 (1:0.6500+dfsg-1, automatic), libnl-3-200:amd64 (3.4.0-1, automatic), novnc-pve:amd64 (1.1.0-1, automatic), libio-stringy-perl:amd64 (2.111-3, automatic), libtirpc3:amd64 (1.1.4-0.4, automatic), fonts-dejavu-core:amd64 (2.37-1, automatic), librrd8:amd64 (1.7.1-2, automatic), cstream:amd64 (3.1.1-1, automatic), libxml-twig-perl:amd64 (1:3.50-1.1, automatic), pve-lxc-syscalld:amd64 (0.9.1-1, automatic), python-pkg-resources:amd64 (40.8.0-1, automatic), libpve-common-perl:amd64 (6.2-2, automatic), libboost-regex1.67.0:amd64 (1.67.0-13+deb10u1, automatic), python-cephfs:amd64 (12.2.11+dfsg1-2.1+b1, automatic), ceph-fuse:amd64 (12.2.11+dfsg1-2.1+b1, automatic), python-ipaddr:amd64 (2.2.0-2, automatic), libgstreamer-plugins-base1.0-0:amd64 (1.14.4-2, automatic), lxc-pve:amd64 (4.0.3-1, automatic), libsndfile1:amd64 (1.0.28-6, automatic), python-urllib3:amd64 (1.24.1-1, automatic), libgoogle-perftools4:amd64 (2.7-1, automatic), libcrypt-openssl-rsa-perl:amd64 (0.31-1+b1, automatic), libtypes-serialiser-perl:amd64 (1.0-1, automatic), qemu-server:amd64 (6.2-15, automatic), libsdl1.2debian:amd64 (1.2.15+dfsg2-4, automatic), ifenslave:amd64 (2.9, automatic), libcrypt-openssl-bignum-perl:amd64 (0.09-1+b1, automatic), libcfg7:amd64 (3.0.4-pve1, automatic), libtemplate-perl:amd64 (2.27-1+b1, automatic), libauthen-pam-perl:amd64 (0.16-3+b6, automatic), libproxmox-backup-qemu0:amd64 (0.7.0-1, automatic), libthai0:amd64 (0.1.28-2, automatic), libxml-namespacesupport-perl:amd64 (1.12-1, automatic), libcommon-sense-perl:amd64 (3.74-2+b7, automatic), libfontconfig1:amd64 (2.13.1-2, automatic), libjs-bootstrap:amd64 (3.4.1+dfsg-1, automatic), libasyncns0:amd64 (0.8-6, automatic), libx11-data:amd64 (2:1.6.7-1+deb10u1, automatic), libboost-atomic1.67.0:amd64 (1.67.0-13+deb10u1, automatic), libxml-libxml-perl:amd64 (2.0134+dfsg-1, automatic), libknet1:amd64 (1.16-pve1, automatic), libsmbclient:amd64 (2:4.9.5+dfsg-5+deb10u1, automatic), smartmontools:amd64 (7.1-pve2, automatic), smbclient:amd64 (2:4.9.5+dfsg-5+deb10u1, automatic), libjemalloc2:amd64 (5.1.0-3, automatic), libtdb1:amd64 (1.3.16-2+b1, automatic), libasound2:amd64 (1.1.8-1, automatic), libglusterfs0:amd64 (5.5-3, automatic), libunwind8:amd64 (1.2.1-10~deb10u1, automatic), genisoimage:amd64 (9:1.1.11-3+b2, automatic), libgraphite2-3:amd64 (1.3.13-7, automatic), pve-kernel-helper:amd64 (6.2-7, automatic), python3-prettytable:amd64 (0.7.2-4, automatic), libboost-program-options1.67.0:amd64 (1.67.0-13+deb10u1, automatic), libevent-2.1-6:amd64 (2.1.8-stable-4, automatic), libc-dev-bin:amd64 (2.28-10, automatic), libdigest-hmac-perl:amd64 (1.03+dfsg-2, automatic), libfile-chdir-perl:amd64 (0.1008-1, automatic), libflac8:amd64 (1.3.2-3, automatic), libiscsi7:amd64 (1.18.0-2, automatic), libnss3:amd64 (2:3.42.1-1+deb10u3, automatic), pve-edk2-firmware:amd64 (2.20200531-1, automatic), libu2f-server0:amd64 (1.1.0-2, automatic), libpve-http-server-perl:amd64 (3.0-6, automatic), x11-common:amd64 (1:7.7+19, automatic), criu:amd64 (3.11-3, automatic), python-idna:amd64 (2.6-1, automatic), libxml-parser-perl:amd64 (2.44-4, automatic), liblinux-inotify2-perl:amd64 (1:2.1-1, automatic), libvorbis0a:amd64 (1.3.6-2, automatic), numactl:amd64 (2.0.12-1, automatic), libgfchangelog0:amd64 (5.5-3, automatic), libharfbuzz0b:amd64 (2.3.1-1, automatic), libipset11:amd64 (6.38-1.2, automatic), libjansson4:amd64 (2.12-1, automatic), libprotobuf17:amd64 (3.6.1.3-2, automatic), xsltproc:amd64 (1.1.32-2.2~deb10u1, automatic), keyutils:amd64 (1.6-6, automatic), libice6:amd64 (2:1.0.9-2, automatic), faketime:amd64 (0.9.7-3, automatic), libcairo2:amd64 (1.16.0-4, automatic), libcpg4:amd64 (3.0.4-pve1, automatic), thin-provisioning-tools:amd64 (0.7.6-2.1, automatic), libavahi-client3:amd64 (0.7-4+b1, automatic), libfile-readbackwards-perl:amd64 (1.05-2, automatic), curl:amd64 (7.64.0-4+deb10u1, automatic), libpango-1.0-0:amd64 (1.42.4-8~deb10u1, automatic), libjs-sphinxdoc:amd64 (1.8.4-1, automatic), libdevel-cycle-perl:amd64 (1.12-1, automatic), libtevent0:amd64 (0.9.37-1, automatic), rpcbind:amd64 (1.2.5-0.3+deb10u1, automatic), libpve-apiclient-perl:amd64 (3.0-3, automatic), libgstreamer1.0-0:amd64 (1.14.4-1, automatic), libattr1-dev:amd64 (1:2.4.48-4, automatic), libjpeg62-turbo:amd64 (1:1.5.2-2+b1, automatic), libqrencode4:amd64 (4.0.2-1, automatic), librados2:amd64 (12.2.11+dfsg1-2.1+b1, automatic), libnet-ip-perl:amd64 (1.26-2, automatic), uidmap:amd64 (1:4.5-1.1, automatic), libcrypt-random-seed-perl:amd64 (0.03-1, automatic), libboost-thread1.67.0:amd64 (1.67.0-13+deb10u1, automatic), libnspr4:amd64 (2:4.20-1, automatic), nfs-common:amd64 (1:1.3.4-2.5+deb10u1, automatic), socat:amd64 (1.7.3.2-2, automatic), libx11-xcb1:amd64 (2:1.6.7-1+deb10u1, automatic), libappconfig-perl:amd64 (1.71-2, automatic), libcorosync-common4:amd64 (3.0.4-pve1, automatic), libfribidi0:amd64 (1.0.5-3.1+deb10u1, automatic), libxslt1.1:amd64 (1.1.32-2.2~deb10u1, automatic), libnetfilter-log1:amd64 (1.0.1-1.1+b1, automatic), libxext6:amd64 (2:1.3.3-1+b2, automatic), libdatrie1:amd64 (0.2.12-2, automatic), python-rbd:amd64 (12.2.11+dfsg1-2.1+b1, automatic), proxmox-ve:amd64 (6.2-2), lxcfs:amd64 (4.0.3-pve3, automatic), libnfsidmap2:amd64 (0.25-5.1, automatic), libboost-system1.67.0:amd64 (1.67.0-13+deb10u1, automatic), liblzo2-2:amd64 (2.10-0.1, automatic), python-protobuf:amd64 (3.6.1.3-2, automatic)
Remove: firmware-linux-free:amd64 (3.4)
Error: Sub-process /usr/bin/dpkg returned an error code (1)
End-Date: 2020-10-29  15:31:26

**Comment by areyer** [comment]
recommends potentially bloat the system

**Comment by gratuxri** [comment]
Without recommends you don't have full functionality of this software. For example you don't have pool on this system.
