### ISSUE TITLE
Selfhealing don't work after first error

### ISSUE THREAD

**Issue by gratuxri** [LinuxHaus/ansible-lihas-proxmox#4]
/var/log/apt/history.log after some retries:
`
Start-Date: 2020-10-29  15:31:31
Commandline: /usr/bin/apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold install pve-headers -o APT::Install-Recommends=no
Install: pve-headers:amd64 (6.2-2), pve-headers-5.4:amd64 (6.2-7, automatic), pve-headers-5.4.65-1-pve:amd64 (5.4.65-1, automatic)
Error: Sub-process /usr/bin/dpkg returned an error code (1)
End-Date: 2020-10-29  15:31:40

Start-Date: 2020-10-29  15:31:43
Commandline: /usr/bin/apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold install haveged -o APT::Install-Recommends=no
Install: libhavege1:amd64 (1.9.1-7, automatic), haveged:amd64 (1.9.1-7)
Error: Sub-process /usr/bin/dpkg returned an error code (1)
End-Date: 2020-10-29  15:31:46

Start-Date: 2020-10-29  15:31:52
Commandline: /usr/bin/apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold install wireguard-dkms -o APT::Install-Recommends=no
Install: libmpc3:amd64 (1.1.0-1, automatic), libmpx2:amd64 (8.3.0-6, automatic), libmpfr6:amd64 (4.0.2-1, automatic), cpp-8:amd64 (8.3.0-6, automatic), binutils:amd64 (2.31.1-16, automatic), cpp:amd64 (4:8.3.0-1, automatic), libitm1:amd64 (8.3.0-6, automatic), gcc:amd64 (4:8.3.0-1, automatic), libasan5:amd64 (8.3.0-6, automatic), libquadmath0:amd64 (8.3.0-6, automatic), dkms:amd64 (2.6.1-4, automatic), libisl19:amd64 (0.20-2, automatic), binutils-x86-64-linux-gnu:amd64 (2.31.1-16, automatic), libgcc-8-dev:amd64 (8.3.0-6, automatic), libtsan0:amd64 (8.3.0-6, automatic), libubsan1:amd64 (8.3.0-6, automatic), make:amd64 (4.2.1-1.2, automatic), gcc-8:amd64 (8.3.0-6, automatic), liblsan0:amd64 (8.3.0-6, automatic), libgomp1:amd64 (8.3.0-6, automatic), binutils-common:amd64 (2.31.1-16, automatic), wireguard-dkms:amd64 (1.0.20200908-1~bpo10+1), libbinutils:amd64 (2.31.1-16, automatic), libatomic1:amd64 (8.3.0-6, automatic), libcc1-0:amd64 (8.3.0-6, automatic), dpkg-dev:amd64 (1.19.7, automatic)
Error: Sub-process /usr/bin/dpkg returned an error code (1)
End-Date: 2020-10-29  15:32:10

Start-Date: 2020-10-29  15:33:38
Commandline: /usr/bin/apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold install proxmox-ve -o APT::Install-Recommends=no
Error: Sub-process /usr/bin/dpkg returned an error code (1)
End-Date: 2020-10-29  15:33:41
`

**Comment by areyer** [comment]
I can't see the actual source of the problem here and can't see this issue on other installations. Unless this is a result of an incomplete /etc/hosts we need more information here.

**Comment by gratuxri** [comment]
On debian default Installation you have 127.0.0.1 $FQDN and not $IP
Just make fresh debian install to reproduce.

**Comment by areyer** [comment]
as stated in README.md already due to you various other bug reports, you need to fix /etc/hosts yourself for now. Unless we require setting host variables we have no way to determine the correct IP for the host for the infrastructure it should be running in. /etc/hosts might become a part of ansible_lihas_common as /etc/network/interfaces already is.
