### ISSUE TITLE
pveproxy failed certificates

### ISSUE THREAD

**Issue by gratuxri** [LinuxHaus/ansible-lihas-proxmox#8]
● pveproxy.service - PVE API Proxy Server
   Loaded: loaded (/lib/systemd/system/pveproxy.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-10-29 16:42:35 CET; 8min ago
  Process: 1516 ExecStartPre=/usr/bin/pvecm updatecerts --silent (code=exited, status=111)
  Process: 1518 ExecStart=/usr/bin/pveproxy start (code=exited, status=0/SUCCESS)
 Main PID: 1519 (pveproxy)
    Tasks: 3 (limit: 4915)
   Memory: 132.9M
   CGroup: /system.slice/pveproxy.service
           ├─1519 pveproxy
           ├─1947 pveproxy worker
           └─1948 pveproxy worker

Oct 29 16:50:59 lab02 pveproxy[1946]: worker exit
Oct 29 16:50:59 lab02 pveproxy[1519]: worker 1944 finished
Oct 29 16:50:59 lab02 pveproxy[1519]: starting 1 worker(s)
Oct 29 16:50:59 lab02 pveproxy[1519]: worker 1947 started
Oct 29 16:50:59 lab02 pveproxy[1947]: /etc/pve/local/pve-ssl.key: failed to load local private key (key_file or key) at /usr/share/perl5/PVE/APIServer/AnyEvent.pm line 173
Oct 29 16:50:59 lab02 pveproxy[1519]: worker 1945 finished
Oct 29 16:50:59 lab02 pveproxy[1519]: starting 1 worker(s)
Oct 29 16:50:59 lab02 pveproxy[1519]: worker 1946 finished
Oct 29 16:50:59 lab02 pveproxy[1519]: worker 1948 started
Oct 29 16:50:59 lab02 pveproxy[1948]: /etc/pve/local/pve-ssl.key: failed to load local private key (key_file or key) at /usr/share/perl5/PVE/APIServer/AnyEvent.pm line 173

It looks like certificates are not created automatically, or /etc/pve is not accesible.

**Comment by gratuxri** [comment]
/etc/pve is not mounted on this system

**Comment by gratuxri** [comment]
It should be mounted from pve-cluster.service

**Comment by areyer** [comment]
you need to have the fqdn in /etc/hosts pointing to a real ip suitable for your setup

**Comment by gratuxri** [comment]
pvecm updatecerts
helps
